CREATE TABLE a_users (
`id` INT(30) NOT NULL AUTO_INCREMENT COMMENT 'id',
`username` VARCHAR(50) NOT NULL COMMENT '用户名',
`password` VARCHAR(100) NOT NULL COMMENT '密码',
`name` VARCHAR(50) NOT NULL COMMENT '姓名',
`sex` INT(1) DEFAULT NULL COMMENT '性别',
`phone` VARCHAR(30) DEFAULT NULL COMMENT '手机号',
`email` VARCHAR(120) DEFAULT NULL COMMENT '邮箱',
`remarks` VARCHAR(1020) DEFAULT NULL COMMENT '备注',
PRIMARY KEY (`id`),
UNIQUE KEY (`username`),
UNIQUE KEY (`phone`),
UNIQUE KEY (`email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='用户表';